# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
# relative_permalinks: true //Remove this line or it will deprecate the lastest version of Jekyll theme.

# Setup
title:               Ting's Square
tagline:             '寫作與程式之路'
description:         'Tings Square: <a href="https://twitter.com/tingtingtour" target="_blank">@tingtingtour</a>的2018生活新專案'
url:                 https://github.com/tingtinghsu
baseurl:             '/blog'
paginate:           5
paginate_path:      "page:num"
excerpt_separator:  '<!-- more -->'

# About/contact
author:
  name:              Ting Ting Hsu
  url:               https://twitter.com/tingtingtour
  email:             tingtinghsu.tw@gmail.com

# Custom vars
version:             1.0.0
plugins: [jekyll-paginate]