# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
# relative_permalinks: true //Remove this line or it will deprecate the lastest version of Jekyll theme.

# Setup
title:               Ting's Square
tagline:             '程式寫作之路'
description:         '@tingtingtour 2018-2019 My Ruby on Rails Project'
url:                 https://github.com/tingtinghsu
baseurl:             '/blog'
paginate:           5
paginate_path:      "page:num"
excerpt_separator:  '<!-- more -->'

# About/contact
author:
  name:              Ting Ting Hsu
  url:               https://twitter.com/tingtingtour
  email:             tingtinghsu.tw[at]gm

# Custom vars
version:             1.0.0
plugins: [jekyll-paginate]